### ISSUE TITLE
URDF Parser

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/amigo_description#1]
The code to parse a URDF model or similar is used in many nodes (e.g., joint trajectory actions, grasp precompute? whole-body controller, simulators etc). It would be convenient if we had one object that took care of that and of which we could easily ask the required info such as joint limits etc.

**Comment by Rayman** [comment]
:+1:

**Comment by reinzor** [comment]
@Timple  is working on this. The following is also a nice addition for automatic compiling of the xacro files:

find_package(xacro REQUIRED)

# Set relative input var

file(GLOB INPUT_FILE urdf/xacro/amigo.urdf.xacro)

# Get input vars

get_filename_component(INPUT_PATH ${INPUT_FILE} ABSOLUTE)
get_filename_component(INPUT_DIR ${INPUT_FILE} PATH)

# Set output path

set(OUTPUT_PATH ${INPUT_DIR}/../amigo.urdf)

# Remove old file

file(REMOVE ${OUTPUT_PATH})

# Construct new file

xacro_add_xacro_file(${INPUT_PATH} ${OUTPUT_PATH})
add_custom_target(description ALL DEPENDS ${OUTPUT_PATH})

**Comment by Timple** [comment]
And since the end of the evening is near, there is also a ROS section about is:
http://wiki.ros.org/xacro#Building_from_CMakeLists.txt
